### ISSUE TITLE
gsutil is not working on windows

### ISSUE THREAD

**Issue by vohtaski** [google-github-actions/setup-gcloud#100]
We are using setup-gcloud. It works perfectly on linux.
However on windows-latest we are having issues with `gsutil` not being found while `gcloud` is working.

This is the config that always returns an error
```
jobs:
  release-win-to-gcs:
    name: Release Win to GCP

    runs-on: windows-latest

    steps:
      - name: Setup gcloud CLI for Dev
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: 'latest'
          project_id: ${{ env.PROJECT_ID }}
          service_account_email: ${{ env.SERVICE_ACCOUNT_EMAIL }}
          service_account_key: ${{ secrets.DEV_GITHUB_CI_CD_SA_KEY}}
      - run: gcloud info

      - run: gsutil
```

Error:
![image](https://user-images.githubusercontent.com/158421/81163232-b69b9900-8f8e-11ea-909c-5021e86480a7.png)

Looks like `gsutil` it's looking python in the wrong place.

**Comment by vohtaski** [comment]
I also tried to use the following setting:
```
      - run: gsutil
        shell: bash
```
and got the following issue, `gcloud info` worked.
![image](https://user-images.githubusercontent.com/158421/81164767-30348680-8f91-11ea-832a-3b7ae14f43fa.png)

**Comment by sethvargo** [comment]
This is probably related to https://github.com/GoogleCloudPlatform/github-actions/blob/dbbc2aaee4ded56fea9d438baacbdd875addfc3f/setup-gcloud/tests/integration-tests.sh#L26-L28.

**Comment by vohtaski** [comment]
Made it work for now with the following:
```
$env:python_version=$(python -c 'import sys; print(\".\".join(map(str, sys.version_info[:3])))')          $env:CLOUDSDK_PYTHON="C:\hostedtoolcache\windows\Python\$env:python_version\x64\python"
```

**Comment by craigdbarber** [comment]
Thanks for raising the issue @vohtaski 
This is indeed a known issue when the Windows distribution of the gcloud-sdk.
Another workaround for Windows is documented here: https://cloud.google.com/storage/docs/gsutil_install#expandable-1-label

**Comment by splix** [comment]
Another workaround. There is `${{env.pythonLocation}}`, which to my understanding comes from `actions/setup-python`, and it contains the base path to Pyhton. The only only issue is that you need that only for Windows, so you have to duplicate everything.

Workflow may look like:
```
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Setup GCP (windows)
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        if: runner.os == 'Windows'
        env:
          CLOUDSDK_PYTHON: ${{env.pythonLocation}}\python.exe
        with: ...

      - name: Use GCP (windows)
        run: gsutil cp ....
        if: runner.os == 'Windows'
        env:
          CLOUDSDK_PYTHON: ${{env.pythonLocation}}\python.exe
```
