### ISSUE TITLE
Feature request: setup-gcloud should support installing optional components

### ISSUE THREAD

**Issue by joshlf** [google-github-actions/setup-gcloud#103]
### TL;DR

The `setup-gcloud` action should support installing optional components. Currently, the only way to install optional components is to add a `run` action to your `ci.yml` like:

```yaml
steps:
  - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
  - name: Install Google Cloud SDK components
    run: yes | gcloud components install beta cloud-firestore-emulator
```

In practice, this approach seems to take a long time to execute, and often flakes.
