### ISSUE TITLE
`region` optional argument in deploy cloud function inputs

### ISSUE THREAD

**Issue by Tofull** [google-github-actions/setup-gcloud#222]
### TL;DR
Remove `region` in [deploy-cloud-functions inputs](https://github.com/google-github-actions/setup-gcloud/tree/master/deploy-cloud-functions#inputs)

**Expected behavior**
According to the current documentation, the region might be given to the cloud function inputs.
Maybe the documentation is not up-to-date.

**Observed behavior**
The github action failed if the `region` optional parameter is provided.
Here is the github action error log:
```
Unexpected input(s) 'region', valid inputs are ['credentials', 'name', 'description', 'project_id', 'source_dir', 'env_vars', 'entry_point', 'runtime', 'vpc_connector', 'service_account_email', 'timeout', 'max_instances', 'event_trigger_type', 'event_trigger_resource', 'event_trigger_service']
```

### Reproduction

**Action YAML**

```yaml
name: Deploy to Google Cloud Function

on:
  # Trigger the workflow on push,
  # but only for the main branch
  push:
    branches:
      - main

# Environment variables available to all jobs and steps in this workflow
env:
  GC_PROJECT: ${{ secrets.GC_PROJECT }}
  GC_KEY: ${{ secrets.GC_KEY }}

jobs:
  setup-deploy:
    name: oush
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          project_id: ${{ secrets.GC_PROJECT }}
          service_account_key: ${{ secrets.GC_KEY }}

      - id: deploy
        uses: GoogleCloudPlatform/github-actions/deploy-cloud-functions@master
        with:
          name: hello_world
          runtime: python38
          entry_point: hello_world_function
          region: northamerica-northeast1
          timeout: 540
          event_trigger_type: google.storage.object.finalize
          event_trigger_resource: hello_world_bucket
```
