### ISSUE TITLE
deploy-cloud-functions reports error when deploying function with cloud.firestore event trigger

### ISSUE THREAD

**Issue by SamuelDudley** [google-github-actions/setup-gcloud#223]
### TL;DR
When using `deploy-cloud-functions` to deploy a function with a `cloud.firestore` event trigger the github action fails with `Error: Cannot read property 'url' of undefined`. Although an error is shown the function deploys correctly.

**Expected behavior**
The action should report a success 

**Observed behavior**
The action reports a failure:

```
Warning: Unexpected input(s) 'region', valid inputs are ['credentials', 'name', 'description', 'project_id', 'source_dir', 'env_vars', 'entry_point', 'runtime', 'vpc_connector', 'service_account_email', 'timeout', 'max_instances', 'event_trigger_type', 'event_trigger_resource', 'event_trigger_service']
Run GoogleCloudPlatform/github-actions/deploy-cloud-functions@master
  with:
    name: new_order
    region: australia-southeast1
    description: send email on new order
    source_dir: functions/new_order
    entry_point: main
    runtime: python38
    event_trigger_type: providers/cloud.firestore/eventTypes/document.create
    event_trigger_resource: projects/***/databases/(default)/documents/orders/***store_id***/orders/***order_id***
    env_vars: SG_SEND_API_KEY=***
  env:
    CLOUDSDK_METRICS_ENVIRONMENT: github-actions-setup-gcloud
    GCLOUD_PROJECT: ***
    GOOGLE_APPLICATION_CREDENTIALS: /home/runner/work/wholesale-web/wholesale-web/a6c0041a-5edd-4db0-a53c-50c9681719f2
Setting project Id from $GCLOUD_PROJECT
Creating a new function deployment
Creating function deployment
Creating function deployment
Creating function deployment
Creating function deployment
Creating function deployment
Creating function deployment
Creating function deployment
Creating function deployment
Creating function deployment
Creating function deployment
Creating function deployment
Creating function deployment
Creating function deployment
Creating function deployment
Creating function deployment
Creating function deployment
Creating function deployment
Creating function deployment
Creating function deployment
Creating function deployment
Creating function deployment
Creating function deployment
Creating function deployment
Creating function deployment
Creating function deployment
Creating function deployment
Creating function deployment
Creating function deployment
Creating function deployment
Creating function deployment
Creating function deployment
Creating function deployment
Function deployment created
Error: Cannot read property 'url' of undefined
```
__Note:__ the warning is not the issue.

### Reproduction

**Action YAML**

```yaml
name: Deploy Functions [PROD]

on:
  push:
    branches: [ master ]
    paths:
      - 'functions/**'

jobs:
  deploy_functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: '${{ secrets.GC_PROJECT_ID_PROD }}'
          service_account_key: ${{ secrets.GC_UPLOAD_FUNCTIONS_PROD }}
          export_default_credentials: true
        
      # The following works without errors
      - id: deploy_test
        uses: GoogleCloudPlatform/github-actions/deploy-cloud-functions@master
        with:
          name: python_test
          region: australia-southeast1
          description: 'a simple test function'
          source_dir: functions/test
          entry_point: hello_world
          runtime: python38

      # The following deploys OK but shows an error in the actions log
      # REF: https://cloud.google.com/functions/docs/calling/cloud-firestore
      - id: deploy_new_order
        uses: GoogleCloudPlatform/github-actions/deploy-cloud-functions@master
        with:
          name: new_order
          region: australia-southeast1
          description: 'send email on new order'
          source_dir: functions/new_order
          entry_point: main
          runtime: python38
          event_trigger_type: 'providers/cloud.firestore/eventTypes/document.create'
          event_trigger_resource: 'projects/${{ secrets.GC_PROJECT_ID_PROD }}/databases/(default)/documents/orders/{store_id}/orders/{order_id}'
          env_vars: 'SG_SEND_API_KEY=${{ secrets.SG_SEND_API_KEY }}'
```

**Additional information**
The `new_order` python function deploys fine and works as expected.
