### ISSUE TITLE
Unable to process command '::add-path::/opt/hostedtoolcache/gcloud/275.0.0/x64/bin' successfully.

### ISSUE THREAD

**Issue by ifndefdeadmau5** [google-github-actions/setup-gcloud#239]
### TL;DR

While running action below error occurs
```shell
Unable to process command '::add-path::/opt/hostedtoolcache/gcloud/275.0.0/x64/bin' successfully.
```

**Expected behavior**
Action should run without error

**Observed behavior**
Error occured

### Reproduction
Use `setup-gcloud` in workflow file
**Action YAML**

```yaml
 - name: Setup gcloud environment
        uses: google-github-actions/setup-gcloud@0.1.2
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          service_account_email: example@appspot.gserviceaccount.com
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
```

**Comment by bharathkkb** [comment]
Hi @ifndefdeadmau5 
This maybe due to https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Could you try with the latest `v0.2.0` release?
```diff
 - name: Setup gcloud environment
-      uses: google-github-actions/setup-gcloud@0.1.2
+      uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          service_account_email: example@appspot.gserviceaccount.com
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
```

**Comment by ifndefdeadmau5** [comment]
@bharathkkb Thanks for quick response! I'll try it out

**Comment by ifndefdeadmau5** [comment]
@bharathkkb still having error
```
Error: Unable to process command '::add-path::/google-cloud-sdk/bin/gcloud' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Error: Unable to process command '::add-path::/google-cloud-sdk/bin/gsutil' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

here's my full .yaml file for reference
```yaml
name: Deploy Google Cloud Function

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build
        run: |
          npm i
          npm run build
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Setup gcloud environment
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          service_account_email: easy-wms@appspot.gserviceaccount.com
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Google Cloud Platform (GCP) CLI - gcloud
        uses: actions-hub/gcloud@307.0.0
        env:
          PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
          APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        with:
          # Arguments for the CLI command
          args: functions deploy invoice-pdf-generator --region=asia-northeast3 --source=. --trigger-http

```

and even though action resulting in failure, looks like deployment itself has completed by the way

**Comment by bharathkkb** [comment]
@ifndefdeadmau5 I tried a repro [here](https://github.com/bharathkkb/test-actions/runs/1410351609?check_suite_focus=true) but it seems to be working. This seems to be coming from `actions-hub/gcloud@307.0.0`. Looks like `actions-hub/gcloud@307.0.0` [does not ](https://github.com/actions-hub/gcloud/blob/17b98fe215012ebf5c69051303d1cd8646ea7691/entrypoint.sh#L59)have the fix.

Additionally, you dont need `actions-hub/gcloud` and `google-github-actions/setup-gcloud` together as they seem to be doing the same thing. With just `setup-gcloud` you can do something like
```
      - name: Setup gcloud environment
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          service_account_email: easy-wms@appspot.gserviceaccount.com
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: deploy-function
        run: gcloud functions deploy invoice-pdf-generator --region=asia-northeast3 --source=. --trigger-http
```

You can also leverage the [native Cloud Function Action](https://github.com/google-github-actions/deploy-cloud-functions).
