### ISSUE TITLE
credentials_file_path warning as invalid action input

### ISSUE THREAD

**Issue by nthypes** [google-github-actions/setup-gcloud#245]
### TL;DR

**Expected behavior**
Should export the credentials to the valid path passed through `credentials_file_path` input options

**Observed behavior**
```
Warning: Unexpected input(s) 'export_default_credentials', valid inputs are ['version', 'service_account_email', 'service_account_key']
Run google-github-actions/setup-gcloud@master
```

### Reproduction

**Action YAML**
```yaml
      - name: setup gcloud credentials
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_ACCOUNT }}
          credentials_file_path: ${{ env.RUNNER_TEMP }}
          export_default_credentials: true
          version: "318.0.0"
```

**Additional information**

The feature https://github.com/google-github-actions/setup-gcloud/pull/213 is not working @ master.

Looks like that `credentials_file_path` dissapeared from `action.yml @ master` branch for some reason.
