### ISSUE TITLE
github action with docker push is failing

### ISSUE THREAD

**Issue by MeenachiSundaram** [google-github-actions/setup-gcloud#258]
https://github.com/google-github-actions/setup-gcloud/blob/3054e12850eac9214961ad22f57bfbe70bc64ac5/example-workflows/cloud-run/cloud-run.yml#L45

```
The push refers to repository [gcr.io/***/meenachisundaram-com]
6f905dd01d9d: Preparing
9bf0d6629c54: Preparing
88ae3975cb22: Preparing
869c0679f18c: Preparing
4eaf0ea085df: Preparing
2c7498eef94a: Preparing
7d2b207c2679: Preparing
5c4e5adc71a8: Preparing
87c8a1d8f54f: Preparing
2c7498eef94a: Waiting
7d2b207c2679: Waiting
5c4e5adc71a8: Waiting
87c8a1d8f54f: Waiting
unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
Error: Process completed with exit code 1.
```

The following role is associated with the Service account 
```
Cloud Build Service Account
Service Account User
Cloud Run Admin
Storage Admin
Viewer
Editor
```

Following API enabled
```
Container registry
Cloud run
```

**Comment by MeenachiSundaram** [comment]
current github action .yaml content

```
name: Build and Deploy a Container

on: [push]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  SERVICE: meenachisundaram-com
  REGION: europe-west4

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true  # Set to true to authenticate the Cloud Run action

    # - name: Authorize Docker push
      # run: gcloud auth configure-docker

    - name: Authorize Docker and Build and Push Container
      run: |-
        gcloud auth configure-docker
        docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }} .
        docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }}
        
    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v0.2.0
      with:
        service: ${{ env.SERVICE }}
        image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }}
        region: ${{ env.REGION }}

    - name: Show Output
      run: echo ${{ steps.deploy.outputs.url }}
```
