### ISSUE TITLE
Unexpected token � in JSON at position 0

### ISSUE THREAD

**Issue by ikegami** [google-github-actions/setup-gcloud#260]
Am I missing something?

```yaml
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ttsclub-bot
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
```

Output:

```
Run google-github-actions/setup-gcloud@master
  with:
    project_id: ttsclub-bot
    service_account_key: ***
    export_default_credentials: true
    version: latest
  env:
    DOTNET_ROOT: /home/runner/.dotnet
/bin/tar xz --warning=no-unknown-keyword -C /home/runner/work/_temp/688bb776-b550-41ff-af02-6e16b18b68ae -f /home/runner/work/_temp/b9ea5158-d4c1-4693-80ee-e3473c426bb7
/opt/hostedtoolcache/gcloud/322.0.0/x64/bin/gcloud --quiet config set project ttsclub-bot
Updated property [core/project].
Successfully set default project
Error: Unexpected token � in JSON at position 0
```
