### ISSUE TITLE
Authenticating inside a composite run 

### ISSUE THREAD

**Issue by etiennebatise** [google-github-actions/setup-gcloud#272]
### Question
We are executing the following steps for all our services in our monorepo:
```yaml
      - name: Authenticate Google Cloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          service_account_email: ${{ secrets....}}
          service_account_key: ${{ secrets.... }}

      - name: Authenticate Google Cloud on Docker
        run: gcloud auth configure-docker

      - name: Update Google Cloud components
        run: gcloud components update
```

As our number of service grows, we're thinking of using [composite run steps](https://docs.github.com/en/actions/creating-actions/creating-a-composite-run-steps-action) to reduce duplication. 

After testing it briefly, the code executes just well in the composite run step action. Nevertheless, it doesn't update the environment of the calling action. In this case, next steps calling `docker pull` on images hosted on google cloud fails.

Is there a way to do such a thing?

**Comment by etiennebatise** [comment]
It turns out this was a chair-to-keyboard interface problem. The composite run step describe above does not actually work because `uses` is not supported in this context. 

The following works though

The workflow
```yaml
....

   steps:
       - name: Authenticate Google Cloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Google Cloud
        uses: ./.github/actions/authenticate-google-cloud

...
```

The action
```yaml
name: 'Setup Google Cloud'
description: 'Handle authentication for Google Cloud on Docker and updates components'
runs:
  using: "composite"
  steps:
    - name: Authenticate Google Cloud on Docker
      run: gcloud auth configure-docker
      shell: bash

    - name: Update Google Cloud components
      run: gcloud components update
      shell: bash
```
