### ISSUE TITLE
Option missing to work with gcloud configurations other than `default`

### ISSUE THREAD

**Issue by headcr4sh** [google-github-actions/setup-gcloud#315]
### TL;DR
My use-case involves working with more than one gcloud configuration within a single GitHub job.
I am therefore looking for a way to specify the "configuration name" when setting up cloud credentials.

### Design

**Action YAML**
```yaml
- name: Set up Cloud SDK (creds-a)
  uses: google-github-actions/setup-gcloud@master
  with:
    configuration_name: config-a
    service_account_key: ${{ secrets.GOOGLE_BACKEND_CREDENTIALS_A }}
    export_default_credentials: false
- name: Set up Cloud SDK (creds-b)
  uses: google-github-actions/setup-gcloud@master
  with:
    configuration_name: config-b
    service_account_key: ${{ secrets.GOOGLE_BACKEND_CREDENTIALS_B }}
    export_default_credentials: false
```

**Resources**
- [gcloud config configurations](https://cloud.google.com/sdk/gcloud/reference/config/configurations)

**Additional information**
I am working on a terraform pipeline where I need one service account key to access the terraform state stored in a GCS bucket and another service account key to perform the actual infrastrucure-as-code/terraform-related tasks
