### ISSUE TITLE
No credentials provided, skipping authentication on: pull_request

### ISSUE THREAD

**Issue by guptamukul-google** [google-github-actions/setup-gcloud#379]
### Question

Trying to setup github action for my private repo and here is the step for setting up gcloud

```
  - name: Set up Cloud SDK
    uses: google-github-actions/setup-gcloud@master
    with:
      service_account_key: ${{ secrets.GCP_SA_KEY }}
      export_default_credentials: true
```

I get `Successfully exported Default Application Credentials` when I set the Github Action **on: [workflow_dispatch]** . 

But when I use the same step **on: pull_request** it gives `No credentials provided, skipping authentication`

![image](https://user-images.githubusercontent.com/9626165/138347645-c66e7634-28e8-4ac0-b451-0a3308ebd138.png)

Not sure why is it not recognizing service_account_key is provided ONLY on: pull_request. Any insights or help is appreciated.
