### ISSUE TITLE
add option for post job cleanup of creds

### ISSUE THREAD

**Issue by marengaz** [google-github-actions/setup-gcloud#382]
### TL;DR
option for post job cleanup of creds

### Design

**Action YAML**

```yaml
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: my-project
          service_account_key: ${{ secrets.MY_SA_KEY }}
          export_default_credentials: true
          post_job_credential_cleanup: true
```

a rudimentary way to do this would be something like:
```
rm -f "$GOOGLE_APPLICATION_CREDENTIALS"
unset GOOGLE_APPLICATION_CREDENTIALS
```

**Additional information**
gives confidence that if a worker is reused, the creds wont still be hanging around
