### ISSUE TITLE
Workload federation credential file

### ISSUE THREAD

**Issue by steveoh** [google-github-actions/setup-gcloud#396]
### TL;DR

I would like to use a federated credential file from the auth action to setup gcloud

### Design

**Action YAML**

```yaml
- id: auth
   name: Authenticate to Google Cloud
   uses: google-github-actions/auth@v0.3.1
   with:
       create_credentials_file: true
       workload_identity_provider: ...
       service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

- uses: google-github-actions/setup-gcloud@master
   with:
        project_id: ${{ secrets.PROJECT_ID }}
        credentials_file_path: ${{ steps.auth.output.credentials_file_path }}
```

**Resources**

- https://cloud.google.com/iam/docs/using-workload-identity-federation#github-actions

**Additional information**

**Comment by bharathkkb** [comment]
You can use it like [this](https://github.com/google-github-actions/auth#configuring-gcloud) today, but we are in the process of making this more seamless.

**Comment by steveoh** [comment]
Yes I have seen that. I think an example of going from a service account json file with `google-github-actions/setup-gcloud` to `google-github-actions/auth` would be appreciated.

Would the following be the equivalent at the moment? 

```yaml
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.3.1
        with:
          create_credentials_file: true
          workload_identity_provider: projects/834965039662/locations/global/workloadIdentityPools/github-action/providers/github-provider
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

      - name: Setup gcloud
        run: |
          gcloud auth login --brief --cred-file=${{ steps.auth.outputs.credentials_file_path }}
          gcloud --quiet config set project ${{ secrets.PROJECT_ID }}
```

**Comment by steveoh** [comment]
> You can use it like [this](https://github.com/google-github-actions/auth#configuring-gcloud) today, but we are in the process of making this more seamless.

Is there an active branch or something or a draft pr I can follow along with the development?

**Comment by sethvargo** [comment]
@steveoh once we're done, you won't have to do anything special; the following will "just work":

```yaml
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.3.1
        with:
          create_credentials_file: true
          workload_identity_provider: ...
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

      - uses: google-github-actions/setup-gcloud@vx.y.z
        run: |-
          gcloud whatever-command # will automatically be authenticated
```

**Comment by steveoh** [comment]
That sounds great. The following would work as well?

```yaml
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.3.1
        with:
          create_credentials_file: true
          workload_identity_provider: ...
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

      - uses: google-github-actions/setup-gcloud@vx.y
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Setup docker
        run: gcloud --quiet auth configure-docker
```

**Comment by sethvargo** [comment]
It would theoretically work, but if you're _only_ authenticating to AR or GCR, it would probably be better to skip gcloud altogether and just use the `docker` action with an oauth token from `auth`. Untested example to show what I mean:

```yaml
- id: auth
  uses: google-github-actions/auth@v0.4.1
  with:
    workload_identity_provider: ...
    service_account: ...
    token_format: access_token

- uses: docker/login-action@v1
  with:
    registry: gcr.io
    username: oauth2accesstoken // yes, this exact value
    password: ${{ steps.auth.outputs.access_token }}
```

If you already have a service account key, you can also auth directly to the registry with that:

```yaml
- uses: docker/login-action@v1
  with:
    registry: gcr.io
    username: _json_key // or _json_key_base64
    password: ${{ secrets.MY_SA_JSON }}
```
