### ISSUE TITLE
Error while running plan with this GA | Terraform 1.0.8

### ISSUE THREAD

**Issue by Sunil-Jacob** [google-github-actions/setup-gcloud#410]
### TL;DR
Getting the below error:

```text
Error: storage.NewClient() failed: dialing: google: error getting credentials using GOOGLE_APPLICATION_CREDENTIALS environment variable: open /home/runner/work/_temp/651d8f6a44067dceb917e2cf: no such file or directory
```

**Expected behavior**
The plan should run successfully

**Observed behavior**
Getting the below error:

```text
Error: storage.NewClient() failed: dialing: google: error getting credentials using GOOGLE_APPLICATION_CREDENTIALS environment variable: open /home/runner/work/_temp/651d8f6a44067dceb917e2cf: no such file or directory
```

### Reproduction

**Action YAML**

```yaml
steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_PRIVATE_KEY }}
          export_default_credentials: true

      - name: Bucket creation DEV
        shell: bash
        run: |
          gsutil ls -b gs://${{ secrets.GCP_PROJECT_NAME}} || (gcloud services enable storage-api.googleapis.com && gsutil mb gs://${{ secrets.GCP_PROJECT_NAME}} && gsutil versioning set on gs://${{ secrets.GCP_PROJECT_NAME}} )
      - name: plan-dev
        uses: dflook/terraform-plan@v1
        env:
          GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
          TERRAFORM_HTTP_CREDENTIALS: |
            github.com/ebomart=${{ secrets.CI_USER}}:${{ secrets.CI_TOKEN}}
        with:
          path: ./
          var_file: environment/dev/variables.tfvars
          label: dev
          backend_config_file: environment/dev/gcs-bucket.tfvars

```

**Additional information**
Are you running custom workers? Doing something atypical? No

**Comment by Sunil-Jacob** [comment]
Hi Team,

This is working when I used SHA `google-github-actions/setup-gcloud@b8f95eb7d716bf9a715eafd169162b93f69ed520`

**Comment by aurecchia** [comment]
I just noticed the same failure. It seems https://github.com/google-github-actions/setup-gcloud/pull/405 accidentally introduced a breaking change.

Just like @Sunil-Jacob I changed my workflow file to explicitly reference a commit SHA (the one used in the last successful build I saw) and then everything is fine.

**Comment by sethvargo** [comment]
Can you share which _step_ the error is coming from? Is it the `Bucket creation DEV` or the `plan-dev` step?

**Comment by Mowee** [comment]
@sethvargo We experience a similar issue. In our case the Default Application Credentials are passed as an environment variable to a docker image but can't be accessed inside the image. For right now I fixed the issue by not using the latest commit anymore and going back a few versions.

**Comment by sethvargo** [comment]
@Mowee can you please share your actions.yml file? I don't think the filesystem is shared with docker containers, so your situation makes sense to me

**Comment by sethvargo** [comment]
It looks like dflook/terraform-plan [is also a Docker-based action](https://github.com/dflook/terraform-plan/blob/master/action.yaml#L59-L62)

**Comment by timcooijmans** [comment]
Same issue here, working with the commit mentioned above:

actions.yaml:
```yaml
name: 'Terragrunt Review@Test'
on:
  - pull_request
env:
  tf_version: 'latest'
  tg_version: 'latest'
  tf_working_dir: './test/'
jobs:
  terragrunt:
    name: 'Terragrunt'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: Set up Google Cloud access
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.TEST_GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
      - name: 'Terragrunt Init'
        uses: the-commons-project/terragrunt-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tg_actions_version: ${{ env.tg_version }}
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: false
        env:
          TF_INPUT: false
```

**Comment by sethvargo** [comment]
It looks like Docker-based actions [don't mount `RUNNER_TEMP`](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#docker-container-filesystem), so the credentials aren't available on the shared filesystem.

**Comment by timcooijmans** [comment]
Oh, I agree this is a difficult case, but I don't think it should suddenly break like this. Is there an alternative by using the `credentials_file_path` option to force it back?

**Comment by Mowee** [comment]
@sethvargo Sure we are using this workflow:

```yaml
name: Rotate GCP service account key
#on:
#  schedule:
#    - cron: '0 12 * * 1'
on: [workflow_dispatch]
jobs:
  rotate:
    name: rotate gcp key
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_INFRA_KEY }}
          export_default_credentials: true
      - name: rotate gcp keys
        uses: miklosn/github-action-rotate-gcp-key@main
        with:
          projectId: "example"
          serviceAccount: "github-actions@example.iam.gserviceaccount.com"
          personalAccessToken: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
          repositories: ${{ github.repository }}
          secretName: "GCP_SA_INFRA_KEY"
```

The docker image runs as follows: `/usr/bin/docker run [..] -e GOOGLE_APPLICATION_CREDENTIALS `

I switched our workflow to `google-github-actions/setup-gcloud@b8f95eb7d716bf9a715eafd169162b93f69ed520` and it works.
