### ISSUE TITLE
"gcloud  alpha storage cp" command fails because of missing "google-crc32c" binary

### ISSUE THREAD

**Issue by fleroux514** [google-github-actions/setup-gcloud#416]
### TL;DR
`gcloud  alpha storage cp` command fails because of missing `google-crc32c` binary

**Expected behavior**
Able to use this workflow:

```
      - name: Authenticate to Google
        id: 'auth'
        uses: 'google-github-actions/auth@v0.3.1'
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.GCP__GHA__WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          create_credentials_file: true
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
      - name: Download archive from Google Storage
        run: |
          gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
          gcloud --quiet alpha storage cp gs://test.txt ./downloads
```
**Observed behavior**
```
Copying gs://test.txt to file://./downloads/test.txt
ERROR: This download was skipped since the google-crc32c
binary is not installed, and Python hash computation will likely
throttle performance. You can change this by installing the binary
by running "/usr/bin/python3 -m pip install google-crc32c --target /opt/hostedtoolcache/gcloud/365.0.1/x64/lib/third_party" or
modifying the "storage/check_hashes" config setting.
```

**Additional information**
Running the workflow on `ubuntu-latest`

**Comment by sethvargo** [comment]
Looks like we might need to install some packages.
https://cloud.google.com/storage/docs/gsutil/addlhelp/CRC32CandInstallingcrcmod

**Comment by fleroux514** [comment]
@sethvargo All the packages listed in your link seem to be installed in a workflow running on `ubuntu-latest`.

The current workaround is to add this line prior to the 'gcloud alpha storage' command.

```
sudo pip install google-crc32c==1.3.0 --target /usr/lib/google-cloud-sdk/lib/third_party
```

**Comment by AlWol** [comment]
> Looks like we might need to install some packages.
> https://cloud.google.com/storage/docs/gsutil/addlhelp/CRC32CandInstallingcrcmod

Fgbjmk

**Comment by sethvargo** [comment]
Hi @fleroux514 

I just tried to reproduce this and it seems to work for me:

```yaml
steps:
- uses: 'actions/checkout@v2'

- id: 'auth'
  uses: 'google-github-actions/auth@v0'
  with:
    workload_identity_provider: 'projects/416438230019/locations/global/workloadIdentityPools/my-pool/providers/github'
    service_account: 'test-sa@sv-actions-test.iam.gserviceaccount.com'

- id: 'setup-gcloud'
  uses: 'google-github-actions/setup-gcloud@v0'
  with:
    install_components: 'alpha'

- id: 'download'
  run: |-
    gcloud alpha storage cp gs://sv-actions-test/file.txt ./
    ls -alh .
```

How large is the file?
