### ISSUE TITLE
Unable to setup multiple times with different projects in the same job

### ISSUE THREAD

**Issue by tylerbrandt** [google-github-actions/setup-gcloud#418]
### TL;DR

I have a workflow that uses `google-github-actions/setup-gcloud` multiple times, with a different `project_id` and `service_account_key` in each. Prior to f38d54f0d75ec3e1b27429833f635cb308c71cd4, this workflow worked without issue, but now whichever script is _second_ always fails. The error message suggests that the service account from the first setup run is still in use.

### Expected behavior

Each script runs with the credentials defined by whatever project/service account was setup last.

### Observed behavior

Both scripts run with the credentials defined by whatever project/service account was setup first (reordering the job steps confirms this).

The second script thus errors with:
```
ERROR: (gcloud.app.versions.list) User [***@***-prod.iam.gserviceaccount.com] does not have permission to access apps instance [scribeai-test] (or it may not exist): The caller does not have permission
```

### Action YAML

```yaml
name: Cleanup Versions
on:
  schedule:
    # Every hour at :05
    - cron: '5 * * * *'
  workflow_dispatch:
jobs:
  Cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          # Keep version in sync wih .nvmrc.
          node-version: 15.5.1
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v1
        with:
          path: node-modules-cache
          key: ${{ github.workflow }}-node-modules-${{ hashFiles('**/package.json', '**/yarn.lock') }}
      - name: Restore node_modules cache
        if: steps.cache-node-modules.outputs.cache-hit == 'true'
        run: tools/node-modules-cache.sh restore
      - name: Install dependencies
        run: yarn
      - name: Check yarn.lock
        run: yarn check-yarn-lock
      - name: Save node_modules cache
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: tools/node-modules-cache.sh save
      - name: Set up gcloud (prod)
        uses: google-github-actions/setup-gcloud@master
        with:
          export_default_credentials: true
          project_id: ***-prod
          service_account_key: ${{ secrets.GCP_CREDENTIALS_PROD }}
      - name: Cleanup Versions (prod)
        run: yarn cleanup-versions --stopUnusedVersions --execute
      - name: Set up gcloud (test)
        uses: google-github-actions/setup-gcloud@master
        with:
          export_default_credentials: true
          project_id: ***-test
          service_account_key: ${{ secrets.GCP_CREDENTIALS_TEST }}
      - name: Cleanup Versions (test)
        run: yarn cleanup-versions --stopUnusedVersions --project scribeai-test --execute
```

### Additional information

I confirmed this is a regression by pinning the commit hash to 94faef24d2af9aed96d8838c7252ae4f7165dc76
