### ISSUE TITLE
Latest version breaks our build with credentials error

### ISSUE THREAD

**Issue by depsypher** [google-github-actions/setup-gcloud#427]
### TL;DR

Started getting this error with version v0.3.0:

Error: google-github-actions/setup-gcloud failed with: Error parsing credentials: Unexpected end of JSON input
Ensure your credentials are base64 encoded or validate JSON format:

### Expected behavior

No error and successful build

### Observed behavior

Failed build

### Action YAML

```yaml
- name: Setup gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          export_default_credentials: true
```

### Additional information

We were on master, and switching back to this fixes it for us:

```
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          export_default_credentials: true
```
