### ISSUE TITLE
Usage guide for Workload Identity Federation does not include `permissions` block

### ISSUE THREAD

**Issue by glasnt** [google-github-actions/setup-gcloud#430]
### TL;DR

Actions require additional permissions when using WIF, and the "Usage" guide on this repo does not include the [permissions block](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#permissions). 

### Expected behavior

Usage sample would work.

### Observed behavior

```
Run google-github-actions/auth@v0.4.2
Error: google-github-actions/auth failed with: Error: Error message: Unable to get ACTIONS_ID_TOKEN_REQUEST_URL env variable
```

### Action YAML

```yaml
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - id: auth
      uses: google-github-actions/auth@v0.4.1
      with:
        workload_identity_provider: 'projects/FOO/locations/global/workloadIdentityPools/BAR/providers/BIZ'
        service_account: 'FOO@BAR.iam.gserviceaccount.com'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0

    - name: Use gcloud CLI
      run: gcloud info
```

### Additional information

[Usage guide from google-github-actions/setup-gcloud](https://github.com/google-github-actions/auth#usage)
