### ISSUE TITLE
Unable to resolve `google-github-actions/setup-gcloud@master`

### ISSUE THREAD

**Issue by humbertowoody** [google-github-actions/setup-gcloud#451]
### TL;DR

Hi!

Our pipelines broke because of this change, we assume is just switching from `master` to `main`. However, we wanted to ask if this change is final? And why release this change 2 days before Christmas? :(

This broke all our pipelines and really didn't wanted to update everything given the holidays. Perhaps there's an easy fix we can apply instead of revisiting all of them? Thanks in advance!

### Expected behavior

To setup the action as normally.

### Observed behavior

The branch name has changed from `master` to `main` so it can't be loaded.

### Action YAML

```yaml
- name: Set GCP service account
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
```
```


### Additional information

This change impacts all our workflows (90+), if this change is a must, we can do it, but just to corroborate with you guys that it is indeed the expected approach.
