### ISSUE TITLE
Unable to resolve action `google-github-actions/setup-gcloud@master`, unable to find version `master`

### ISSUE THREAD

**Issue by jsakas** [google-github-actions/setup-gcloud#453]
### TL;DR

We just started receiving this error, is it expected?

```
Error: Unable to resolve action `google-github-actions/setup-gcloud@master`, unable to find version `master`
```

Our setup:

```
    - name: Setup GCP
      uses: google-github-actions/setup-gcloud@master
      with:
        version: latest
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY_DEV }}
```

### Action YAML

```yaml
- name: Setup GCP
      uses: google-github-actions/setup-gcloud@master
      with:
        version: latest
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY_DEV }}
```
```


### Additional information

_No response_
