### ISSUE TITLE
What is the best way to use an emulator from this action in a workflow?

### ISSUE THREAD

**Issue by mattwelke** [google-github-actions/setup-gcloud#502]
I need to run tests in GitHub Actions where the tests connect to the Pub/Sub emulator. GitHub's recommended way to start something in the background that runs throughout your workflow, for things in your workflow to use, appears to be "services" (https://docs.github.com/en/actions/using-containerized-services/about-service-containers).

But I wasn't able to get this to work. I wasn't able to find a way to override the command used to run the Docker image. People suggested workarounds like creating a container where you use the gcloud Docker image as a base image and use your own command to start whichever emulator you need. But I don't like to idea of having to set up and maintain a system to keep an up to date Pub/Sub emulator image available for our workflows.

I was able to put together a workflow that appeared to work. The entire example, with the readme documenting my findings, the workflow file, and the Go source code that the workflow runs, is at https://github.com/mattwelke/github-actions-pubsub-emulator-example.

Just in case that repo isn't available at some point in the future, here's the YAML for the workflow, which I think is the important part. What makes it work for me is adding ` &` to a step that starts the emulator so that it runs in the background and my Go code can then run, connecting to it:

```yaml
on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: 'Install Cloud SDK'
        uses: google-github-actions/setup-gcloud@v0
        with:
          install_components: 'beta,pubsub-emulator'
      - name: 'Start Pub/Sub emulator'
        run: |
          gcloud beta emulators pubsub start --project=testproject --host-port=0.0.0.0:8085 &
      - name: Run program
        env:
          PUBSUB_EMULATOR_HOST: 'localhost:8085'
        run: |
          go run main.go
```

Is this the recommended way to do this use case? If not, is there a better way?

**Comment by mattwelke** [comment]
For some added context, we're porting our workflows over from CircleCI, and we have this at the top of one of our CircleCI jobs:

```yaml
version: 2.1
jobs:
  run-unit-tests:
    docker:
      - image: circleci/golang:1.13
...
      - image: google/cloud-sdk
        command: gcloud beta emulators bigtable start --host-port=0.0.0.0:8086
```

It looks like we were able to use a command to control how the `google/cloud-sdk` image starts, and that's how we got it to start the emulator as a CircleCI service for the entire job to use.
