### ISSUE TITLE
issue with v0 and master version  : google-github-actions/setup-gcloud@v0

### ISSUE THREAD

**Issue by kundan-krushna-shende-db** [google-github-actions/setup-gcloud#504]
### TL;DR

We have an issue with user workflows where they are trying to setup gcloud. That setup is getting timeout with below error.
Error: google-github-actions/setup-gcloud failed with: connect ETIMEDOUT 142.251.36.46:443 

Actually we allow the actions on github enterprise level policies. Actions (github.com)
Here earlier we had below two entries for gcloud. 
google-github-actions/setup-gcloud@daadedc81d5f9d3c06d2c92f49202a3cc2b919ba,
google-github-actions/setup-gcloud@master,

But then later we started getting waring in the workflow that master is going to be unsupported so start using v0. That’s why we have added this one there and all users started using this v0 version of gcloud setup. 
google-github-actions/setup-gcloud@v0,

However as I mentioned above all github actions are getting failed with the v0 version since last week.

### Expected behavior

google-github-actions/setup-gcloud@v0,
 was working earlier so want that to be working.

### Observed behavior

google-github-actions/setup-gcloud@v0,
giving timeout error

### Action YAML

```yaml
- name: setup gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
```

### Log output

```text
Run google-github-actions/setup-gcloud@v0
  with:
    project_id: XXX
    service_account_key: ***
    version: latest
    export_default_credentials: false
    cleanup_credentials: true
```

### Additional information

This is impacting all our user since last 1 week. Also want to know why this is failing with timeout on that IP for v0 version.
