### ISSUE TITLE
Enable support for node 16

### ISSUE THREAD

**Issue by maduq1** [google-github-actions/setup-gcloud#523]
### TL;DR

The workflows on machines using node16 break when downloading the action with the following error:

`System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node16' is not supported, use 'docker' or 'node12' instead.')`

This is happening on a self-hosted runner, which have been recently updated to run node16 as node12 is getting EOL.

### Action YAML

```yaml
name: deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Branch or tag to deploy to the selected environment"
        required: true
        default: "master"
      environment:
        description: "Environment to deploy to (test|dev|prod)"
        required: true
        default: "dev"

jobs:
  manual-deploy:
    runs-on:
      - self-hosted
      - ${{ github.event.inputs.environment }}-environment

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.version }}
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install dependencies
        run: |
          npm ci
          cd db
          npm ci
          cd ..
      - name: Auth in GCloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets[env.sa_key] }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets[env.project_id] }}
      - name: Enable GCloud Beta commands
        run: gcloud components install beta --quiet
```

### Log output

```text
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node16' is not supported, use 'docker' or 'node12' instead.')
```
