### ISSUE TITLE
Setup fails with 'Invalid value for "audience"'

### ISSUE THREAD

**Issue by iben12** [google-github-actions/setup-gcloud#546]
### TL;DR

I use workload identity federation and after auth step finishes successfully the gcloud setup fails with _Invalid value for "audience"_.

The output of the auth step is as follows:
```
Run google-github-actions/auth@v0
  with:
    workload_identity_provider: projects/1234567890/locations/global/workloadIdentityPools/github/attribute.repository/.../...
    service_account: ...
    create_credentials_file: true
    export_environment_variables: true
    cleanup_credentials: true
    access_token_lifetime: 600s
    access_token_scopes: https://www.googleapis.com/auth/cloud-platform
    id_token_include_email: false
Created credentials file at "/home/runner/work/.../.../gha-creds....json"
```

### Expected behavior

GCloud SDK is set up correctly

### Observed behavior

Setup step fails

### Action YAML

```yaml
...
jobs:
  setup:
    permissions:
      contents: "read"
      id-token: "write"
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: "projects/1234567890/locations/global/workloadIdentityPools/github/attribute.repository/<my-org>/<my-repo>"
          service_account: "<svc-account-email@iam.gserviceaccount.com>"
    
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"
```

### Log output

```text
Error: google-github-actions/setup-gcloud failed with: failed to execute command `gcloud --quiet auth login --cred-file /home/runner/work/.../.../gha-creds-c258de8274a37813.json`: ERROR: gcloud crashed (OAuthError): ('Error code invalid_request: Invalid value for "audience". This value should be the full resource name of the Identity Provider. See https://cloud.google.com/iam/docs/reference/sts/rest/v1/TopLevel/token for the list of possible formats.', '{"error":"invalid_request","error_description":"Invalid value for \\"audience\\". This value should be the full resource name of the Identity Provider. See https://cloud.google.com/iam/docs/reference/sts/rest/v1/TopLevel/token for the list of possible formats."}')
```
