### ISSUE TITLE
upgrade to 1.0.0 broke the ssh connection

### ISSUE THREAD

**Issue by cpanato** [google-github-actions/setup-gcloud#590]
### TL;DR

after we update to the release 1.0.0 our workflow broken with the follwoing error

```
ERROR: (gcloud.compute.ssh) User [None] does not have permission to access users instance [None] (or it may not exist): End user credentials must match the user specified in the request. Request for user [ None] does not match the credential for [github-actions@xxxxxxxx.iam.gserviceaccount.com].
```

### Action YAML

```yaml
the snippet workflow code is


  - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d # v0.8.1
      with:
        # Default is to generate a key file, which is automatically configured for use with gcloud.
        workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ env.SERVICE_ACCOUNT }}

    - uses: google-github-actions/setup-gcloud@ee9693ff89cdf73862b8a13988f6a71070e8fc58 # v0.6.0
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Install gke-gcloud-auth-plugin
      if: ${{ env.BASTION_ACCESS == 'true' }}
      run: gcloud --quiet components install gke-gcloud-auth-plugin

    - uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # 2.0.0
      with:
        terraform_version: 1.1.9
        terraform_wrapper: false

    - name: connect to bastion
      if: ${{ env.BASTION_ACCESS == 'true' }}
      run: |
        gcloud compute ssh --zone ${{ env.BASTION_ZONE }} ${{ env.BASTION_NAME}} --tunnel-through-iap --project ${{ env.PROJECT_ID }} -- -N -D 8118 &
        sleep 60
```
```


### Log output

```text
ERROR: (gcloud.compute.ssh) User [None] does not have permission to access users instance [None] (or it may not exist): End user credentials must match the user specified in the request. Request for user [ None] does not match the credential for [github-actions@xxxxxxxx.iam.gserviceaccount.com].
```
```


### Additional information

_No response_
