### ISSUE TITLE
python3.8: not found

### ISSUE THREAD

**Issue by clementhemidy** [google-github-actions/setup-gcloud#592]
### TL;DR

Hello guys,

We have this error when we use your action since this morning.

Error: google-github-actions/setup-gcloud failed with: failed to execute command `gcloud --quiet components install gke-gcloud-auth-plugin`: /opt/hostedtoolcache/gcloud/410.0.0/x64/bin/gcloud: 182: exec: python3.8: not found

Do you have any idea what going on ?

### Action YAML

```yaml
- name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.0.1
        with:
          install_components: 'gke-gcloud-auth-plugin'
```

### Log output

```text
Error: google-github-actions/setup-gcloud failed with: failed to execute command `gcloud --quiet components install gke-gcloud-auth-plugin`: /opt/hostedtoolcache/gcloud/410.0.0/x64/bin/gcloud: 182: exec: python3.8: not found
```
