### ISSUE TITLE
Authenticaton warning when using application default credentials

### ISSUE THREAD

**Issue by jorob16** [google-github-actions/setup-gcloud#594]
### TL;DR

I'm running a self-hosted GitHub Actions runner on a GKE cluster. Permissions are handled through application default credentials (Workload Identity) and my workflow works correctly (no authorization errors). Unfortunately `setup-gcloud` still spits out a warning: `**Warning**: No authentication found for gcloud, authenticate with `google-github-actions/auth`.`

![afbeelding](https://user-images.githubusercontent.com/91264722/202873095-d1124aee-0308-4153-85b6-c91b466c182a.png)
![afbeelding](https://user-images.githubusercontent.com/91264722/202873357-1111b074-ada1-441c-a07d-1c6997b8c2b2.png)

### Expected behavior

I did not expect a warning, considering that the workflow works correctly and interacts with multiple GCP services for which authorization is definitely required.

### Observed behavior

An authentication warning is displayed in the workflow logs and as an annotation under the job overview.

### Action YAML

```yaml
name: CICD Bumpversion master
on: 
  push:
    branches:
      - master
    paths:
      - cicd-bumpversion/**
      - .github/workflows/cicd-bumpversion-master.yaml
jobs:
  build-image:
    name: Build and push image
    runs-on: [self-hosted, **REDACTED**]
    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t **REDACTED**/cicd-bumpversion:latest .
        working-directory: cicd-bumpversion/
      - name: Push image to Container Registry
        run: |
          gcloud auth configure-docker
          docker push **REDACTED**/cicd-bumpversion:latest
```
