### ISSUE TITLE
resource-config failure

### ISSUE THREAD

**Issue by geret1** [google-github-actions/setup-gcloud#595]
### TL;DR

I'm trying to export existing resources in my GCP project to terraform files by using GHA. It's failing due to stdin issues with parameters.

### Expected behavior

To obtain the output terraform file with all GCP resources.

### Observed behavior

It seems that the gcloud command is not detecting input parameters.

### Action YAML

```yaml
resources:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Authenticate via Workload Identity Federation
        id: wif
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: ${{ env.WIF_PROVIDER }}
          service_account: ${{ env.WIF_SA }}
      
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      
      - name: 'Export terraform'
        id: export_terraform
        run: |
          gcloud --quiet beta resource-config bulk-export --resource-format=terraform
```

### Log output

```text
error in 'config-connector' version '1.93.0': cannot supply input on stdin with the 'project' parameter
ERROR: (gcloud.beta.resource-config.bulk-export) The bulk-export command could not finish correctly.
```
```


### Additional information

_No response_

**Comment by sethvargo** [comment]
Hi @geret1 

Can you please provide the [debug logs](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging)? The error says that it's prompting for the "--project" flag, but that fails since it's not an interactive environment.

The project should be set by the `auth` action, and the debug logs will help determine why that's not happening.

**Comment by geret1** [comment]
Thanks! What step do you need, auth or resource-config?

**Comment by sethvargo** [comment]
The entire debug logs for the workflow.

**Comment by geret1** [comment]
Here it is ;) 

[debug-logs.zip](https://github.com/google-github-actions/setup-gcloud/files/10106377/debug-logs.zip)

**Comment by sethvargo** [comment]
Hi @geret1 - It looks like the gcloud command requires a `--project` flag and it is explicitly not inherited from core/project. Therefore, you'll need to pass in a project ID as a flag:

```yaml
- name: 'Export terraform'
  id: export_terraform
  run: |
    gcloud --quiet beta resource-config bulk-export --project ${{ env.PROJECT_ID // TODO }} --resource-format=terraform
```

**Comment by geret1** [comment]
It's more strange because the output is the same even with the `--project` parameter. It looks like the `bulk-export` command doesn't accept parameters.

[6_Export terraform.txt](https://github.com/google-github-actions/setup-gcloud/files/10107365/6_Export.terraform.txt)

**Comment by sethvargo** [comment]
Hmm - that's weird. What happens if you run locally?

**Comment by geret1** [comment]
Yep, totally weird. In local with `gcloud auth login` and owner role works without problems but with WIF something strange is happening.

Putting verbosity to debug in gcloud I see the following command:

```
DEBUG: Executing command: ['/opt/hostedtoolcache/gcloud/410.0.0/x64/bin/config-connector', '--oauth2-token', 'ya29.c.b0Aa9VdyldCADhe_eKYYB9x9zOauhJmhyEr5CJ9HBxRID9NmMHs3QxjvgM5CJIVwIWuf69Yaae549DIQRdUgYMElf7D0NN0qyWlBume6VDKjI_p9q3jAaRS508EJfK10AHpmizd1wWWfRRSGDZ_Qq2iVN5bNCAkiMiELFpie8mHH4s2aRM_ksa7wXenCJ6T0N732HBaNpcO7GCxAKpsAV8Eb43tO7mFPCnRVdb70A0sjhuOkPbeyqeKgSpXdEpYlbJx3SFR-UN5B8LKEQzGa-eaq770iUFoA1E18UDlQqe33mRSFktGo9LDML-7gN0yLGEVoy4SlrwyrZ2pNavirek_ZsaVfXs6KFHSRyW0AlTNcBq9FVPI4Y7sn2eszZpyc09LTo8CVbE8VZr3AcVFFhdJlXRpzzK9XKU4fNhLBnIc8wjIki70u9vBrrgvc8zqutxmbOYf18wfJkmjHUcqlGdGU_6lmzZ1_oSG7NnFAH091OWmAOBp-OQGYJazlMhRCb-4uA1JRy6JGK0G4mdYsCPl_b76sGl2ZcDvKT6XdBoGUJZi2SH1Mb8aufYwAjQwDV0ePgoaNB1nnpQQvGbHMWoNhs................................................................................................................................................................................................................................................................................................................................................................................................................................', 'bulk-export', '--on-error', 'ignore', '--project', 'my-project, '--resource-format', 'hcl', '--iam-format', 'none']
```

In local differs the `oauth2-token` (the dots I mean)

**Comment by sethvargo** [comment]
@geret1 revoke your tokens please :). Those are valid auth credentials.

**Comment by sethvargo** [comment]
Hi @geret1 that definitely feels like a gcloud bug. I would recommend filing an issue with the gcloud team: https://cloud.google.com/sdk/docs/getting-support

**Comment by geret1** [comment]
ooooook thanks anyway for the support!

**Comment by sethvargo** [comment]
No problem - sorry, we don't control the gcloud CLI itself, just the installation and setup.

**Comment by sethvargo** [comment]
Oh, you could have google-github-actions/auth generate you an access_token that you pass in to the CLI manually as a workaround.

```yaml
- uses: 'google-github-actions/auth@v1'
  id: 'auth'
  with: 
    format: 'access_token'

- name: 'Export terraform'
  id: export_terraform
  run: |
    gcloud --quiet beta resource-config bulk-export --oauth2-token=${{ steps.auth.outputs.access_token }} --resource-format=terraform
```

**Comment by fruwe** [comment]
@geret1 I am having the same issue. Did you ever found a working solution?
@sethvargo Unfortunately, the `--oauth2-token` option does not exist; I tried the `--access-token-file` option, but that also throws the same error

**Comment by fruwe** [comment]
Using the `script` command worked for me 🎉 

Here is roughly how it looks like:

```yaml
export:
  name: Find drifts
  runs-on: ubuntu-latest
  permissions:
    contents: read
    id-token: write
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - id: auth
      name: "Authenticate to Google Cloud"
      uses: "google-github-actions/auth@v1"
      with:
        workload_identity_provider: "xxx"
        service_account: "xxx"
    - name: "Set up Cloud SDK"
      uses: "google-github-actions/setup-gcloud@v1"
    - name: Install components
      run: |
        gcloud components install beta --quiet
        gcloud components install config-connector --quiet
    - id: export
      name: Export GCP resources
      working-directory: compare
      run: script --return --quiet -c "gcloud beta resource-config bulk-export --resource-format=terraform --project=xxx" /dev/null
```
