### ISSUE TITLE
getting this error 'The key 'id-token' is not allowed' 

### ISSUE THREAD

**Issue by nitishvu** [google-github-actions/setup-gcloud#609]
### TL;DR

getting the below error now, it was working till yesterday.

 error 'The key 'id-token' is not allowed' 

### Action YAML

```yaml
jobs:
  build:
    timeout-minutes: 60
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - id: 'gcp-auth'
        name: 'Auth into GCP'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'XX'
          service_account: 'XX'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
```
