### ISSUE TITLE
Please drastically speed up gcloud installs

### ISSUE THREAD

**Issue by andaag** [google-github-actions/setup-gcloud#610]
### TL;DR

Since the gke-gcloud-auth-plugin is required our build times in quite many places got *way* worse. I have some jobs where google-github-actions/setup-gcloud@v1 takes over a minute, and all the other steps are less than 5s.

### Detailed design

The step we are currently using to install gcloud sdk:
```
    - name: "Setup gcloud sdk"
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: '412.0.0'
        install_components: gke-gcloud-auth-plugin
```
