### ISSUE TITLE
Authentication can take up to 20mn on self-hosted runners in k8s (GCP) 

### ISSUE THREAD

**Issue by MI-LA01** [google-github-actions/setup-gcloud#620]
### TL;DR

<img width="987" alt="Screenshot 2023-03-09 at 12 32 07" src="https://user-images.githubusercontent.com/197890/224024454-81cc92c7-cfc4-4f34-8188-5f73b0403e6c.png">

### Expected behavior

Something faster

### Observed behavior

This is happening almost for each build

### Action YAML

```yaml
jobs:
  build:
    runs-on: [self-hosted]
    
    outputs:
      helm_package: $IMAGE-${{ steps.clear-ref-heads-from-version.outputs.value }}
      branch: ${{ steps.clear-ref-heads-from-version.outputs.value }}

    steps:
    - uses: azure/setup-kubectl@v3
      id: install

    - name: Debug github event name 
      run: |
          echo ${{ github.event_name }}

    - name: Checkout
      uses: actions/checkout@v2.3.3
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
    
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.ARTIFACTORY_GCLOUD }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
```
```


### Log output

_No response_

### Additional information

Current runner version: '2.302.1'
