### ISSUE TITLE
"Certificate has expired" error when retrieving latest version of SDK

### ISSUE THREAD

**Issue by bkonicek-calm** [google-github-actions/setup-gcloud#625]
### TL;DR

Our CI builds are failing running this action when attempting to determine the latest SDK version.

I see the same is happening on CI jobs in this repo as well. https://github.com/google-github-actions/setup-gcloud/actions/runs/4515232467/jobs/7952271303#step:7:41

### Expected behavior

I expect it to successfully install and set up the gcloud SDK.

### Observed behavior

Our workflow fails with the error 

```
Run google-github-actions/setup-gcloud@v1
Error: google-github-actions/setup-gcloud failed with: failed to retrieve versions from https://raw.githubusercontent.com/google-github-actions/setup-cloud-sdk/main/data/versions.json: certificate has expired
```

### Action YAML

```yaml
name: PR Pipeline
on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  swiftlint-and-unit-tests:
    runs-on: [self-hosted, macOS]
    permissions:
      contents: 'read'
      id-token: 'write'
      issues: write
      pull-requests: write
    steps:

    - name: setup-git-credentials
      uses: de-vri-es/setup-git-credentials@v2.0.10
      with:
        credentials: https://${{ secrets.SA_USER }}:${{ secrets.TOKEN }}@github.com/

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Bundle install
      run: bundle install --path vendor/bundle

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        token_format: access_token
        project_id: ************
        service_account: *************
        workload_identity_provider: ************

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
```

### Log output

```text
Run google-github-actions/setup-gcloud@v1
Error: google-github-actions/setup-gcloud failed with: failed to retrieve versions from https://raw.githubusercontent.com/google-github-actions/setup-cloud-sdk/main/data/versions.json: certificate has expired
```
