### ISSUE TITLE
"No authentication found" warning is thrown when using Application Default Credentials

### ISSUE THREAD

**Issue by isarkis** [google-github-actions/setup-gcloud#628]
### TL;DR

We use Application Default Credentials on our self-hosted runners.  As such, we don't need to use google-github-actions/auth action.  With such set up, google-github-actions/setup-gcloud throws the following warning:

Warning: No authentication found for gcloud, authenticate with `google-github-actions/auth`

### Expected behavior

Warning shouldn't be thrown as we are already authenticated.

### Observed behavior

Warning is thrown.

### Action YAML

```yaml
job:
  job_id:
    steps:
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'
```
