### ISSUE TITLE
gcloud crashed (AttributeError): 'bool' object has no attribute 'lower'

### ISSUE THREAD

**Issue by erwanriou** [google-github-actions/setup-gcloud#632]
### TL;DR

Since 5 minutes ago this is currently happening within all my pipelines.

### Expected behavior

to authenticate to gcloud...

### Observed behavior

action build failed due to the error

### Action YAML

```yaml
name: deploy_******_scheduler

on:
  push:
    branches:
      - develop

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: ******
  GKE_ZONE: ******
  DEPLOYMENT_NAME: ******
  IMAGE: ******

jobs:
  deploy:
    name: Deploy ****** in ******
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # AUTH GOOGLE
      - name: Setup Gcloud credentials
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GKE_JSON_CREDENTIALS }}
      - name: Auth Gcloud
        uses: "google-github-actions/setup-gcloud@v1"
      # AUTH DOCKER
      - name: Auth Docker
        run: gcloud --quiet auth configure-docker
      # AUTH GKE
      - name: Auth GKE
        uses: "google-github-actions/get-gke-credentials@v1"
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          project_id: ${{ env.PROJECT_ID }}

      # BUILD IMAGE
      - name: Build Docker
        run: echo -e "GITHUB_TOKEN=${{ secrets.CI_TOKEN }}" > .env.local && docker build -t gcr.io/$PROJECT_ID/$IMAGE -f infra/Dockerfile.production .
      # DEPLOY IMAGE
      - name: Publish Docker
        run: docker push gcr.io/$PROJECT_ID/$IMAGE
      # DEPLOY GKE
      - name: Deploy GKE
        run: kubectl rollout restart deployment $DEPLOYMENT_NAME && kubectl get services -o wide
```

**Comment by zenyui** [comment]
@erwanriou I was about to open the same issue! we locally hotfixed by pinning gcloud version `400.0.0`
```yaml
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1.1.0'
      with:
        version: '400.0.0'
```

TBD which version broke it.

**Comment by erwanriou** [comment]
Ok so at least i can temporarly fix my pipelines. Thank!

**Comment by nyoungstudios** [comment]
418 is the latest that works

I ran a matrix job like so
```yaml
name: Gcloud Test

on:
  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419]

    steps:  
      - uses: actions/checkout@v3

      # Set up gcloud to update libs
      - name: GCloud Auth
        uses: google-github-actions/auth@v0
        with:
          project_id: ${{ secrets.GKE_PROJECT }}
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: ${{ matrix.version }}
```
