### ISSUE TITLE
setup-gcloud failing on windows 2019 github runners

### ISSUE THREAD

**Issue by SC6333** [google-github-actions/setup-gcloud#655]
### TL;DR

Hi,

I am seeing a recent failure with the setup-gcloud step in windows 2019 runner with the following error message

google-github-actions/setup-gcloud failed with: failed to execute command `gcloud.cmd --quiet auth _***gcloud_email****_ --key-file -`: The system cannot find the path specified.

I am running the auth step before it and I can see the key file has been generated and is present in the right path.
The same sequence of steps also works when I switch the runner to an ubuntu one.
I am using python 3.9 in the setup and a regular windows 2019 github runner.

Can you help with this?

### Expected behavior

Gcloud gets successfully setup in the windows runner

### Action YAML

```yaml
name: Builds SDK_C

on:
  push:
    branches:
      - master
      - MPSDK-2185
  pull_request:
    branches:
      - master

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  Build-and-Upload-SDK:
    runs-on: windows-2019
    steps:

      - name: Checkout code
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
      - name: Set Build Number
        run: echo "BUILD_NUMBER=$( git rev-list --count HEAD )" >> $env:GITHUB_ENV

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Export gcloud related env variable
        run: echo "CLOUDSDK_PYTHON=/usr/bin/python" >> $env:GITHUB_ENV

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCE_SA_KEY }}
          project_id: spg-zpc-tools
          export_environment_variables: true
      
      - name: Show Dir
        run: dir

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: '5.0.x'
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.1.1

      - name: Setup VSTest.console.exe
        uses: darenm/Setup-VSTest@v1.2

      - name: Setup SHFB
        uses: Bassman2/setup-SHFB@v1
        with:
          version: 2022.10.15.0

      - name: Install Community Tasks
        run: |
          choco install msbuild.communitytasks
```
