### ISSUE TITLE
windows-2019 runner -> setup-gcloud reports old version of Python installed even when running previously the setup-python step

### ISSUE THREAD

**Issue by shermanericts** [google-github-actions/setup-gcloud#659]
### TL;DR

Using the windows-2019 runner, the setup-gcloud fails even when I previously run the setup-python github action to be 3.8 or 3.10.  Even setting CLOUDSDK_PYTHON to the correct path doesn't correct this behavior.

### Observed behavior

I would expect the setup-gcloud not to fail.

### Action YAML

```yaml
name: "Phil Prep"
on: 
  schedule:
    - cron: "0 0 * * 1" # every Monday at 00:00
  workflow_dispatch:
jobs:
  phil-prep:
    permissions:
      contents: write
      id-token: write
      packages: write
    runs-on: windows-2019
    env:  
      GH_TOKEN: ${{ github.token }}
    environment: main
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: 'auth service account'
        uses: 'google-github-actions/auth@v1'
        with:
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
          workload_identity_provider: ${{ secrets.WORKLOAD_ID_PROVIDER }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8' 
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: Prep For Phil.zip
        run: |
          python -m ensurepip
          python -m pip install -r .github/ci-bin/requirements.txt
          python ./.github/ci-bin/phil.py --action=prep
```
```


### Log output

https://gist.github.com/shermanericts/9ce10d6a3aea6ba6c2df9532790b81b0


### Additional information

_No response_
