### ISSUE TITLE
Spurious warning auth is unavailabe, but gcloud works

### ISSUE THREAD

**Issue by joshgc** [google-github-actions/setup-gcloud#670]
### TL;DR

We run out GHA on self-hosted runners on GKE. When using v1 like...

```
Run google-github-actions/setup-gcloud@v1
  with:
    skip_install: false
    version: latest
```
we get the following warning

```
Warning: No authentication found for gcloud, authenticate with `google-github-actions/auth`.
```

However gcloud works fine.

### Detailed design

Looking at the code here, I expect the issue is that no credentials file is present but gcloud is able to find the GCE Metadata server. This seems like a safe path so I'm wondering if we could drop the warning?
