### ISSUE TITLE
Can't find 'action.yml', 'action.yaml' or 'Dockerfile' for action 'GoogleCloudPlatform/github-actions/setup-gcloud@main'.

### ISSUE THREAD

**Issue by basit511** [google-github-actions/setup-gcloud#675]
### TL;DR

Deploying a Docker Image to GCP - GCR

### Action YAML

```yaml
#Deploy.yml
name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@main
      with:
        project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
        service_account_key: ${{ secrets.GCLOUD_KEY }}
        export_default_credentials: true
        
    - name: Build Docker Image
      run: |
        docker build -t gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/hello.py:${{ github.sha }} .
        docker push gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/hello.py:${{ github.sha }}

    - name: Configure kubectl
      run: |
        gcloud container clusters get-credentials ${{ secrets.GCLOUD_CLUSTER_NAME }} --zone ${{ secrets.GCLOUD_ZONE }}

    - name: Deploy to GKE
      run: |
        kubectl set image deployment/hello.py-deployment hello.py=gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/hello.py:${{ github.sha }}
```

### Log output

```text
Current runner version: '2.311.0'
Operating System
Runner Image
Runner Image Provisioner
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v2' (SHA:ee0669bd1cc54295c223e0bb666b733df41de1c5)
Download action repository 'GoogleCloudPlatform/github-actions@main' (SHA:5a5f7b85fca43e76e53463acaa9d408a03c98d3a)
Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' for action 'GoogleCloudPlatform/github-actions/setup-gcloud@main'.
```

**Comment by sethvargo** [comment]
Hi @basit511 - that's because `GoogleCloudPlatform/github-actions/setup-gcloud@main` does not exist. The GitHub action is `google-github-actions/setup-gcloud@v2`. Where did you find `GoogleCloudPlatform/github-actions/setup-gcloud@main`?

**Comment by basit511** [comment]
Still the same 
![image](https://github.com/google-github-actions/setup-gcloud/assets/101107213/a6652202-2e8e-4d62-a022-df686e88e695)

**Comment by muradkhan995** [comment]
### Verify Action Repository and Version
_Updated Action Configuration_
```
- name: Set up Google Cloud SDK
  uses: google-github-actions/setup-gcloud@v1
  with:
    project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
    service_account_key: ${{ secrets.GCLOUD_KEY }}
    export_default_credentials: true
```

 _Update Workflow YAML_
```

name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
        service_account_key: ${{ secrets.GCLOUD_KEY }}
        export_default_credentials: true
        
    - name: Build Docker Image
      run: |
        docker build -t gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/hello.py:${{ github.sha }} .
        docker push gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/hello.py:${{ github.sha }}

    - name: Configure kubectl
      run: |
        gcloud container clusters get-credentials ${{ secrets.GCLOUD_CLUSTER_NAME }} --zone ${{ secrets.GCLOUD_ZONE }}

    - name: Deploy to GKE
      run: |
        kubectl set image deployment/hello.py-deployment hello.py=gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/hello.py:${{ github.sha }}

```
